"""Static knowledge base for smart offline fallback across all agents."""
from __future__ import annotations

import re

INDUSTRY_KB: dict[str, dict] = {
    "hr_tech": {
        "name": "HR Tech / CareerTech",
        "keywords": r"interview|resume|job search|career|hiring|recruit|employment|talent|onboard|workforce",
        "market_size": "$28.5B",
        "growth_rate": 14.3,
        "market_demand_score": 8.5,
        "competition_score": 6.2,
        "feasibility_score": 8.8,
        "competitors": [
            {"name": "LinkedIn Learning", "stage": "Public (MSFT)", "weakness": "Generic, not practice-focused"},
            {"name": "Interviewing.io", "stage": "$13M raised", "weakness": "Expensive peer scheduling"},
            {"name": "Pramp", "stage": "Bootstrapped", "weakness": "No AI personalisation"},
            {"name": "HackerRank", "stage": "$58M raised", "weakness": "Coding-only, no soft-skill coaching"},
        ],
        "pain_points": [
            "Candidates get no actionable feedback after failed interviews",
            "Human coaching costs $150–$300 per hour",
            "No way to track skill improvement over time",
            "Practice interviews are hard to schedule with busy professionals",
        ],
        "reddit_signals": [
            "r/cscareerquestions – 'Failed 5 interviews, no idea why – no feedback given'",
            "r/jobs – 'Wish there was an AI that could analyse my answers in real time'",
            "HN thread – 'Interview prep is broken; we need structured AI roleplay'",
        ],
        "sentiment_score": 7.8,
        "revenue_models": ["SaaS subscription ($19–$49/mo)", "B2B enterprise licensing", "Pay-per-session credits"],
        "tech_stack": {
            "frontend": "React / Next.js",
            "backend": "FastAPI (Python)",
            "database": "PostgreSQL + Redis",
            "ai_layer": "OpenAI Whisper + GPT-4o",
            "infra": "Railway / Render",
        },
        "mvp_features": [
            "User authentication & profile",
            "AI-powered mock interview (text + voice)",
            "Instant answer scoring & feedback",
            "Progress tracking dashboard",
            "Question bank by role & difficulty",
        ],
        "risks": [
            {"risk": "LLM hallucination in feedback", "mitigation": "Add human reviewer tier for premium plan"},
            {"risk": "Low retention after job offer", "mitigation": "Add continuous upskilling paths"},
            {"risk": "Competitors adding AI fast", "mitigation": "Focus on niche (e.g., only FAANG prep)"},
        ],
        "target_users": "Junior–mid-level software engineers and business graduates job hunting",
        "business_model": "B2C SaaS with B2B licensing arm",
        "moat": "Proprietary answer quality dataset + domain-specific fine-tuning",
    },

    "edtech": {
        "name": "EdTech / Learning Platform",
        "keywords": r"education|learn|student|teacher|tutor|course|school|university|training|skill|certification",
        "market_size": "$404B",
        "growth_rate": 16.5,
        "market_demand_score": 8.2,
        "competition_score": 5.8,
        "feasibility_score": 8.5,
        "competitors": [
            {"name": "Coursera", "stage": "Public (COUR)", "weakness": "Passive video-based learning"},
            {"name": "Udemy", "stage": "Public (UDMY)", "weakness": "Low quality control on content"},
            {"name": "Khan Academy", "stage": "Non-profit", "weakness": "No personalised AI paths"},
            {"name": "Duolingo", "stage": "Public (DUOL)", "weakness": "Gamification over depth"},
        ],
        "pain_points": [
            "One-size-fits-all curriculum doesn't match individual pace",
            "No real-time feedback on understanding gaps",
            "High dropout rate (>90 %) for online courses",
            "Teachers lack data on which students need intervention",
        ],
        "reddit_signals": [
            "r/learnprogramming – 'Courses don't adapt when I'm stuck; I just give up'",
            "r/Teachers – 'I can't track 30 students' comprehension in real time'",
            "HN – 'Adaptive learning is the future; nobody has cracked it yet'",
        ],
        "sentiment_score": 7.5,
        "revenue_models": ["Subscription ($9–$29/mo)", "Institution licensing", "Certification fees"],
        "tech_stack": {
            "frontend": "React",
            "backend": "Django / FastAPI",
            "database": "PostgreSQL",
            "ai_layer": "OpenAI API + LangChain",
            "infra": "AWS / Vercel",
        },
        "mvp_features": [
            "Personalised learning path generator",
            "AI tutor chatbot per topic",
            "Quiz with instant explanation",
            "Progress analytics for students",
            "Parent / teacher dashboard",
        ],
        "risks": [
            {"risk": "Content accuracy of AI explanations", "mitigation": "Expert review layer for core modules"},
            {"risk": "High customer acquisition cost", "mitigation": "School partnerships for B2B distribution"},
            {"risk": "Engagement drop-off", "mitigation": "Gamification + streak mechanics"},
        ],
        "target_users": "K-12 students, working professionals, and self-learners aged 16–40",
        "business_model": "B2C subscription + B2B institution licensing",
        "moat": "Adaptive learning engine trained on student response data",
    },

    "healthtech": {
        "name": "HealthTech / Digital Health",
        "keywords": r"health|medical|doctor|patient|hospital|clinic|wellness|fitness|mental health|therapy|nutrition|diet",
        "market_size": "$211B",
        "growth_rate": 18.6,
        "market_demand_score": 9.0,
        "competition_score": 5.5,
        "feasibility_score": 7.2,
        "competitors": [
            {"name": "Headspace", "stage": "$215M raised", "weakness": "Meditation-only, no diagnosis"},
            {"name": "Babylon Health", "stage": "Listed / struggling", "weakness": "High cost, poor UX"},
            {"name": "Ada Health", "stage": "$121M raised", "weakness": "Symptom checker only"},
            {"name": "Calm", "stage": "$218M raised", "weakness": "Passive content, no interaction"},
        ],
        "pain_points": [
            "Average GP wait time is 3+ weeks in many countries",
            "Mental health stigma prevents people seeking help",
            "Patients forget 40–80 % of clinical information post-visit",
            "Chronic disease management has no daily feedback loop",
        ],
        "reddit_signals": [
            "r/mentalhealth – 'Waiting 2 months for a therapist slot; wish AI could help bridge the gap'",
            "r/diabetes – 'I need something that tracks my meals AND explains my glucose spikes'",
            "HN – 'AI health assistants will replace first-line GP appointments within 5 years'",
        ],
        "sentiment_score": 8.2,
        "revenue_models": ["B2C subscription ($14–$39/mo)", "Insurance partnership", "Hospital SaaS licensing"],
        "tech_stack": {
            "frontend": "React Native (mobile-first)",
            "backend": "FastAPI",
            "database": "PostgreSQL + HL7 FHIR",
            "ai_layer": "GPT-4o + Med-PaLM 2",
            "infra": "AWS HIPAA-compliant",
        },
        "mvp_features": [
            "Symptom checker with triage",
            "AI health journal & mood tracker",
            "Medication reminder system",
            "Telehealth appointment booking",
            "Progress analytics & reports",
        ],
        "risks": [
            {"risk": "Regulatory compliance (HIPAA, GDPR)", "mitigation": "Partner with legal-health consultant from day 1"},
            {"risk": "Medical liability", "mitigation": "Clear disclaimer; triage-only, not diagnosis"},
            {"risk": "Data privacy breaches", "mitigation": "End-to-end encryption + audit trail"},
        ],
        "target_users": "Adults 25–55 managing chronic conditions or mental health",
        "business_model": "B2C subscription + B2B insurance/hospital licensing",
        "moat": "Longitudinal personal health dataset + HIPAA-certified infrastructure",
    },

    "fintech": {
        "name": "FinTech / Financial Technology",
        "keywords": r"finance|payment|bank|invest|crypto|wallet|money|fintech|loan|budget|saving|trading|stock|insurance",
        "market_size": "$340B",
        "growth_rate": 20.5,
        "market_demand_score": 8.8,
        "competition_score": 5.0,
        "feasibility_score": 7.0,
        "competitors": [
            {"name": "Robinhood", "stage": "Public (HOOD)", "weakness": "Gamification criticism, limited research"},
            {"name": "Mint / Credit Karma", "stage": "Acquired by Intuit", "weakness": "Legacy UX, ad-heavy"},
            {"name": "Plaid", "stage": "$13.4B valuation", "weakness": "B2B infrastructure, not consumer"},
            {"name": "Revolut", "stage": "$33B valuation", "weakness": "Regulatory challenges in US"},
        ],
        "pain_points": [
            "Most people have no idea where their money goes each month",
            "Investment advice is inaccessible for low-income earners",
            "Credit scoring is opaque and unfair to young people",
            "Cross-border payments are still expensive and slow",
        ],
        "reddit_signals": [
            "r/personalfinance – 'I need an app that just tells me what to do with my money in plain English'",
            "r/investing – 'Robo-advisors are great but I want AI that explains WHY'",
            "HN – 'Embedded finance is eating every vertical'",
        ],
        "sentiment_score": 7.6,
        "revenue_models": ["Transaction fees (0.5–1.5 %)", "Premium subscription ($7–$15/mo)", "B2B API licensing"],
        "tech_stack": {
            "frontend": "React Native",
            "backend": "Node.js / FastAPI",
            "database": "PostgreSQL + TimescaleDB",
            "ai_layer": "OpenAI + Plaid API",
            "infra": "AWS with SOC-2 compliance",
        },
        "mvp_features": [
            "Bank account aggregation (read-only)",
            "AI spending categorisation & insights",
            "Budget goal setting & alerts",
            "Investment portfolio overview",
            "AI financial advisor chatbot",
        ],
        "risks": [
            {"risk": "Financial regulation (SEC, FCA)", "mitigation": "Start with information-only, no advice license"},
            {"risk": "Bank API access (Plaid costs)", "mitigation": "Use open banking APIs in EU first"},
            {"risk": "User trust with financial data", "mitigation": "SOC-2, read-only access, no credential storage"},
        ],
        "target_users": "Millennials and Gen-Z aged 22–38 managing personal finances",
        "business_model": "Freemium B2C with API licensing to fintechs",
        "moat": "Proprietary spending-pattern AI model + user financial graph",
    },

    "ecommerce": {
        "name": "E-Commerce / Marketplace",
        "keywords": r"shop|store|marketplace|buy|sell|ecommerce|retail|product|vendor|supplier|dropship|inventory",
        "market_size": "$6.3T",
        "growth_rate": 9.8,
        "market_demand_score": 7.5,
        "competition_score": 4.2,
        "feasibility_score": 8.0,
        "competitors": [
            {"name": "Shopify", "stage": "Public (SHOP)", "weakness": "No AI-native personalisation"},
            {"name": "Amazon", "stage": "Public (AMZN)", "weakness": "Seller trust issues, commoditised"},
            {"name": "Etsy", "stage": "Public (ETSY)", "weakness": "Niche handmade only"},
            {"name": "WooCommerce", "stage": "WordPress ecosystem", "weakness": "Technical complexity"},
        ],
        "pain_points": [
            "Small sellers spend 4+ hours/week on product descriptions and SEO",
            "Cart abandonment averages 70 % with no smart recovery",
            "Customer service queries take 24+ hours to respond",
            "Inventory forecasting is manual and error-prone",
        ],
        "reddit_signals": [
            "r/ecommerce – 'I need AI to write my product listings; I sell 500 SKUs'",
            "r/entrepreneur – 'Abandoned cart recovery emails feel spammy; AI personalisation would help'",
            "HN – 'AI-native commerce is the next wave after social commerce'",
        ],
        "sentiment_score": 6.9,
        "revenue_models": ["SaaS subscription ($29–$299/mo)", "GMV commission (1–2 %)", "Add-on app marketplace"],
        "tech_stack": {
            "frontend": "Next.js",
            "backend": "FastAPI / Node.js",
            "database": "PostgreSQL + Elasticsearch",
            "ai_layer": "OpenAI API + Recommendation engine",
            "infra": "Vercel + AWS RDS",
        },
        "mvp_features": [
            "AI product description generator",
            "Smart search & recommendation engine",
            "Automated abandoned cart recovery",
            "Inventory demand forecasting",
            "Customer service AI chatbot",
        ],
        "risks": [
            {"risk": "Amazon / Shopify replication", "mitigation": "Focus on vertical-specific niche"},
            {"risk": "Payment processor risk", "mitigation": "Use Stripe with escrow for marketplaces"},
            {"risk": "Fraud and fake reviews", "mitigation": "ML fraud detection + verified purchase badges"},
        ],
        "target_users": "SMB e-commerce sellers and D2C brands with <$5M revenue",
        "business_model": "SaaS platform + transaction fees",
        "moat": "Merchant sales-performance dataset for AI optimisation",
    },

    "saas": {
        "name": "B2B SaaS / Productivity Tool",
        "keywords": r"saas|software|platform|tool|automation|workflow|dashboard|analytics|productivity|crm|erp|api|integration",
        "market_size": "$232B",
        "growth_rate": 18.2,
        "market_demand_score": 8.0,
        "competition_score": 5.5,
        "feasibility_score": 8.5,
        "competitors": [
            {"name": "Notion", "stage": "$10B valuation", "weakness": "Complex for non-technical users"},
            {"name": "Airtable", "stage": "$11.7B valuation", "weakness": "Expensive at scale"},
            {"name": "Monday.com", "stage": "Public (MNDY)", "weakness": "No AI-native workflows"},
            {"name": "Zapier", "stage": "$5B valuation", "weakness": "No intelligent decision-making"},
        ],
        "pain_points": [
            "Teams switch between 10+ tools daily, losing context",
            "Workflow automation requires technical knowledge",
            "Reporting is manual and always out of date",
            "Onboarding new employees takes 2–4 weeks",
        ],
        "reddit_signals": [
            "r/productivity – 'I waste 2 hours a day just finding information across tools'",
            "r/startups – 'We need one AI workspace that understands our entire business'",
            "HN – 'The future of SaaS is AI agents doing the work, not humans'",
        ],
        "sentiment_score": 7.3,
        "revenue_models": ["Per seat subscription ($10–$50/mo)", "Usage-based pricing", "Enterprise contracts"],
        "tech_stack": {
            "frontend": "React + TypeScript",
            "backend": "FastAPI / Node.js",
            "database": "PostgreSQL + Redis",
            "ai_layer": "OpenAI API + Langchain",
            "infra": "AWS / GCP",
        },
        "mvp_features": [
            "Core workflow builder (drag & drop)",
            "AI task automation engine",
            "Team collaboration space",
            "Integrations with Slack / Gmail / Notion",
            "Real-time analytics dashboard",
        ],
        "risks": [
            {"risk": "Feature parity with incumbents", "mitigation": "Win on AI depth, not feature breadth"},
            {"risk": "Long enterprise sales cycles", "mitigation": "Start with SMB self-serve, land and expand"},
            {"risk": "Integration maintenance burden", "mitigation": "Use unified API layer (Merge.dev)"},
        ],
        "target_users": "Operations teams and founders at companies with 10–200 employees",
        "business_model": "Per-seat SaaS with enterprise tier",
        "moat": "Workflow automation dataset + cross-tool context graph",
    },

    "ai_product": {
        "name": "AI-Native Product",
        "keywords": r"\bai\b|machine learning|gpt|llm|generative|neural|prediction|nlp|computer vision|chatbot|copilot|agent",
        "market_size": "$196B",
        "growth_rate": 36.1,
        "market_demand_score": 9.2,
        "competition_score": 5.0,
        "feasibility_score": 7.8,
        "competitors": [
            {"name": "OpenAI / ChatGPT", "stage": "$157B valuation", "weakness": "Generic, not domain-specific"},
            {"name": "Anthropic / Claude", "stage": "$61B valuation", "weakness": "API-only, no application layer"},
            {"name": "Cohere", "stage": "$2.2B valuation", "weakness": "B2B focus, no consumer UX"},
            {"name": "Perplexity AI", "stage": "$9B valuation", "weakness": "Search-only use case"},
        ],
        "pain_points": [
            "Generic AI lacks domain-specific knowledge",
            "Enterprises can't trust AI with proprietary data",
            "AI outputs are hard to verify and audit",
            "Building custom AI is expensive and slow",
        ],
        "reddit_signals": [
            "r/MachineLearning – 'ChatGPT is great but I need something fine-tuned to my industry'",
            "r/artificial – 'AI agents that actually execute tasks end-to-end are the next frontier'",
            "HN – 'The application layer on top of LLMs is worth more than the models themselves'",
        ],
        "sentiment_score": 8.5,
        "revenue_models": ["API usage pricing", "SaaS subscription ($29–$199/mo)", "Enterprise licensing"],
        "tech_stack": {
            "frontend": "React / Streamlit (prototype)",
            "backend": "FastAPI + LangChain",
            "database": "PostgreSQL + Pinecone (vector DB)",
            "ai_layer": "GPT-4o / Groq LLaMA 3.3",
            "infra": "Modal / Railway",
        },
        "mvp_features": [
            "Domain-specific AI assistant",
            "RAG pipeline over private documents",
            "Structured output & data extraction",
            "Human-in-the-loop review workflow",
            "Usage analytics & cost dashboard",
        ],
        "risks": [
            {"risk": "LLM provider dependency", "mitigation": "Abstract model layer, support multiple providers"},
            {"risk": "Rapid commoditisation", "mitigation": "Focus on proprietary data moat, not model capability"},
            {"risk": "Hallucination in critical decisions", "mitigation": "Confidence scoring + human review gate"},
        ],
        "target_users": "Enterprises and SMBs wanting AI automation without ML expertise",
        "business_model": "Usage-based API + SaaS dashboard",
        "moat": "Domain fine-tuned model + proprietary evaluation dataset",
    },

    "general": {
        "name": "Tech Startup",
        "keywords": r".*",
        "market_size": "$50B+",
        "growth_rate": 12.0,
        "market_demand_score": 7.5,
        "competition_score": 6.0,
        "feasibility_score": 7.8,
        "competitors": [
            {"name": "Direct competitors", "stage": "Various", "weakness": "Lack domain focus"},
            {"name": "Horizontal platforms", "stage": "Established", "weakness": "Not purpose-built for your niche"},
        ],
        "pain_points": [
            "Users lack a purpose-built solution for this specific problem",
            "Existing tools require too much manual effort",
            "Current solutions are expensive or inaccessible",
            "No AI-native approach exists in this space yet",
        ],
        "reddit_signals": [
            "Multiple community threads confirm the problem is real and underserved",
            "Users are building manual workarounds with spreadsheets and scripts",
        ],
        "sentiment_score": 7.0,
        "revenue_models": ["SaaS subscription", "Freemium with premium tier", "Usage-based pricing"],
        "tech_stack": {
            "frontend": "React / Next.js",
            "backend": "FastAPI (Python)",
            "database": "PostgreSQL",
            "ai_layer": "OpenAI API",
            "infra": "Railway / Render",
        },
        "mvp_features": [
            "Core problem-solving feature",
            "User authentication & profiles",
            "AI-powered automation layer",
            "Analytics & reporting",
            "API / integration layer",
        ],
        "risks": [
            {"risk": "Unclear differentiation", "mitigation": "Nail one micro-niche before expanding"},
            {"risk": "Building before validating", "mitigation": "Launch landing page, collect 100 emails first"},
            {"risk": "Team capability gaps", "mitigation": "Hire one domain expert early"},
        ],
        "target_users": "Early adopters in your target segment",
        "business_model": "SaaS with usage-based pricing",
        "moat": "Domain-specific data network effect",
    },
}


def detect_industry(idea: str) -> dict:
    text = idea.lower()
    for key, data in INDUSTRY_KB.items():
        if key == "general":
            continue
        if re.search(data["keywords"], text):
            return data
    return INDUSTRY_KB["general"]
